[dependencies]
std = {features = ["panic_unwind"]}
#test = {features = ["panic_unwind"]}


#cc = ficken
#linker = "mips-linux-gnu-gcc"

[build]
target = "mipsel-linux-gnu-gcc"
#CC = "mips-linux-gnu-gcc"

